### PR TITLE
Add third party notices

### PR DESCRIPTION
**Pull request by ArinGhazarian**
## What's changing?

Per Microsoft's guidelines, this PR adds all third party licenses for all OSS projects that `gh-actions-importer` uses. The PR has two parts:

1. Adding the third party notices file and facilitating its generation 
2. Keeping the `ThirdPartyNotices.txt` up to date by utilizing an extra CI linting task

First, kinda like what we do for GitHub Enterprise Importer (GEI), a `licenses.txt` file was generated by [ThirdLicense](https://github.com/pleonex/ThirdLicense) global tool and was places in `.licenses` directory. This file will serve as our source of truth and as a reference for the `Validate Licenses` CI step. In case of any changes (e.g. a license change for a package or an addition of a new package) the validate licenses step will fail and we need to manually re-generate both `licenses.txt` and the `ThirdPartyNotices.txt` files.

To generate the `licenses.txt`, first the `ThirdLicense` global tool needs to be installed if not installed already:
```shell
dotnet tool install --global ThirdLicense
```

then a new license can be generated with the following command:
```shell
thirdlicense --project src/ActionsImporter.sln --output .licenses/licenses.txt
```
note that it assumes the current directory is `github/gh-actions-importer`. Once the `licenses.txt` file is generated the CI step will pass. 

Second, the actual `ThirdPartyNotices.txt` was generated by a helper script I created for facilitating the process of gathering all licenses of both C# and Ruby projects for Actions Importer. To generate a new `ThirdPartyNotices.txt`, run the following command:
```shell
 dotnet run --project src/ActionsImporter.ThirdPartyLicenseGenerator 
```
note that it assumes the current directory is `github/gh-actions-importer` and the `GITHUB_ACCESS_TOKEN` environment variable is set.

**Notes:**
1. Originally I just intended to create a simple `.csx` script file and put it somewhere outside of `src` directory. But because of some probably bugs in `dotnet script` I was forced to create a small `csproj` that only contains the main script.
2. Similar to the `ThirdLicense` tool, the Ruby project uses the [licensed](https://github.com/github/licensed) gem to make sure all licenses are current. The `ThirdPartyLicenseGenerator` tool gathers and appends all Ruby gem licenses to the C# NuGet licenses too.

## How's this tested?

Manually by generating the `ThridPartyNotices.txt` and observing the `Validate Licenses` CI step.

Related to [#6733](https://github.com/github/valet/issues/6733)

### CODE REVIEW

**Comment by begonaguereca** [comment]
I just looked everything  over and it looks good! I would really love it if someone with more experiences with licenses could take a look at this.

**Review by begonaguereca — APPROVED** [review]
I feel better about approving this after his presention on this. ⚡

**Review by brianaj — APPROVED** [review]
Do we need to add any docs for this change?

**Comment by ArinGhazarian** [comment]
> Do we need to add any docs for this change?

The docs are in the private repo.

**Review by brianaj — APPROVED** [review]

**Pull request merged**
