### PR TITLE
Begin to shape integration testing workflow

### PR DESCRIPTION
**Pull request by Chaseshak**
## How's this tested?

Closes [related issues]

### CODE REVIEW

**Comment by jamshed5759** [comment]
This is awesome dammy projects for it solution company.

**Comment by mtrackeros** [comment]
> ## Wyniki testów jednostkowych
> 41 testów ±0 41 ±0 0s ±0s [⏱️](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.9.0/README.md#the-symbols) 1 Pakiety ±0 0 ±0 1 plików [±0 0 ±0 ✔️](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.9.0/README.md#the-symbols) [💤](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.9.0/README.md#the-symbols) [❌](https://github.com/EnricoMi/publish-unit-test-result-action/blob/v2.9.0/README.md#the-symbols)
> 
> Wyniki dla commit [a743ec2](https://github.com/github/gh-actions-importer/commit/a743ec22023499f9855f0c00804ffc096f35dbcd). ± Porównanie z podstawowym zatwierdzeniem [656838b](https://github.com/github/gh-actions-importer/commit/656838bed8b51015444ecb9280179643f70a1a60).
> 
> ♻️ Ten komentarz został zaktualizowany o najnowsze wyniki.

**Comment by ADNANALISALHADABY** [comment]
Ok

**Comment by leviuswafula** [comment]
hello there developer thank you for contributing to the project ,there's only one error that occurred during merging 
kindly revi-site your code and fix a bug

**Comment by xuantuan150495** [comment]
Truy cập

**Pull request closed without merging**
